---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: tools
spec:
  interval: 5m
  targetNamespace: tools
  chart:
    spec:
      # renovate: registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.12.3
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 5m
  values:
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: none
        secret:
          secretName: "${SECRET_DOMAIN/./-}-production-tls"
      ingress:
        hosts:
          core: harbor.${SECRET_DOMAIN}
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          kubernetes.io/tls-acme: 'true'
    externalURL: https://harbor.${SECRET_DOMAIN}
    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          existingClaim: "harbor-pvc"
          subPath: "registry"
          storageClass: "truenas-csi"
        chartmuseum:
          existingClaim: "harbor-pvc"
          subPath: "chartmuseum"
          storageClass: "truenas-csi"
        jobservice:
          jobLog:
            existingClaim: "harbor-pvc"
            subPath: "jobservice"
            storageClass: "truenas-csi"
            size: 0.5Gi
        database:
          existingClaim: "harbor-pvc"
          subPath: "database"
          storageClass: "truenas-csi"
        redis:
          existingClaim: "harbor-pvc"
          subPath: "redis"
          storageClass: "truenas-csi"
        trivy:
          existingClaim: "harbor-pvc"
          subPath: "trivy"
          storageClass: "truenas-csi"
    caSecretName: ""
  valuesFrom:
    - kind: Secret
      name: harbor-helm-values
      valuesKey: values.yaml
